import swaggerAutogen from "swagger-autogen"
import config from "../Config"
import swaggerBodyModel from "../models/swagger/BodyModel"
import swaggerParamsModel from "../models/swagger/ParamsModel"
import path from "path"

const outputFile = "./SwaggerOutput.json"
const endpointsFiles = [
  "../Routes/User.Routes.js",
  "../Routes/Album.Routes.js",
  "../Routes/Auth.Routes.js",
]
const options = {
  openapi: "3.0.3",
}
const doc = {
  info: {
    version: "1.0.0",
    title: "Library API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  servers: [
    {
      url: `http://localhost:${config.port}/`, // url
      description: "Local Server", // name
    },
    {
      url: `http://localhost:${config.port}/sit`, // url
      description: "Sit Server", // name
    },
    {
      url: `http://localhost:${config.port}/prod`, // url
      description: "Prod Server", // name
    },
  ],
  //   host: `localhost:${config.port}`,
  //   basePath: "/",
  //   schemes: ["http", "https"],
  //   consumes: ["application/json"],
  //   produces: ["application/json"],
  //   tags: [
  //     {
  //       name: "User",
  //       description: "Endpoints",
  //     },
  //   ],
  // securityDefinitions: {
  //   api_key: {
  //     type: "apiKey",
  //     name: "api_key",
  //     in: "header",
  //   },
  //   petstore_auth: {
  //     type: "oauth2",
  //     authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
  //     flow: "implicit",
  //     scopes: {
  //       read_pets: "read your pets",
  //       write_pets: "modify pets in your account",
  //     },
  //   },
  // },
  securityDefinitions: {
    bearerAuth: {
      type: "http",
      scheme: "bearer",
      // bearerFormat: "JWT",
    },
  },
  definitions: swaggerBodyModel,
  parameters: swaggerParamsModel,
}

swaggerAutogen(options)(outputFile, endpointsFiles, doc)
// swaggerAutogen(options)(outputFile, endpointsFiles, doc).then(() => {
//   require("../index.js")
// })
