export { default as getAlbum } from "./Get"
// export { default as getOneUser } from "./getOne"
export { default as insertAlbum } from "./Insert"
// export { default as deleteUser } from "./delete"
// export { default as updateUser } from "./update"
